// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommentsVS
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CommentsVSString = "77a569d5-61e8-47ce-9e0f-9477ca6922d4";
        public static Guid CommentsVS = new Guid(CommentsVSString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolbarGroup = 0x0002;
        public const int CommentsSubMenu = 0x0003;
        public const int CommentsSubMenuGroup = 0x0004;
        public const int CommentsToggleGroup = 0x0005;
        public const int CommentsRenderingGroup = 0x0006;
        public const int CommentsSettingsGroup = 0x0007;
        public const int ToggleCommentVisibility = 0x0200;
        public const int ToggleCollapseByDefault = 0x0202;
        public const int SetRenderingModeOff = 0x0203;
        public const int SetRenderingModeCompact = 0x0204;
        public const int SetRenderingModeFull = 0x0205;
        public const int OpenSettings = 0x0206;
    }
}
